Add field type
StarChart-Labs/eclipse-dynamic-templates pull request #2
Opened 2018-12-17 15:27 UTC by desprez

Hi 
First thanks for this plugin : is great tool to give enhancements for the eclipse template.

When I  try to use this plugin with the Builder pattern , I saw that the type is missing si I add it :

ie : ${strfields2:enclosed_bean_fields('private **${type}** ${name};

I hope this update will be useful for others.

2018-12-17 16:53 UTC, romeara commented
Hi - I am glad you've found it useful! 

Thank you for your contribution! I will review it to determine if any adjustments are necessary as soon as I am able.

2018-12-17 16:56 UTC, romeara requested changes
Before I get too deep into the actual changes here, there is an adjustment I would like made, and a question I would like to to ask.

First, please undo the addition of `final` to all the local variables/methods. Personally, I find it extraneous, however if you'd like to make a case for it I think it would be appropriate to open a separate pull request where it can be reviewed/discussed in isolation from the changes that seem to be the main purpose of this pull request.

Second, what is the purpose of the added XML file? We generally only provide examples, not specific templates, and it appears to be a template definition.

Thank you again for taking the time to submit this improvement - I look forward to re-reviewing once the above is addressed :)

2018-12-18 11:23 UTC, desprez commented
Hi, 
1) Done : "final" removed (it's my Eclipse configuration that will add them automatically. I suggest you provide the files (clean up, format) that you use to keep the codebase as you like it.

2) I delete it too.
This is my template sample to use the new type placeholder :
given the bean class "person"
```java
public class Person {

	private String firstName;

	private String lastName;

	private Boolean active;

	// Getters & Setters ommited
}
```
with the followed template :
```xml
private ${enclosing_type}(Builder builder) {
  ${strfields1:enclosed_bean_fields('this.${name} = builder.${name};', '${newline}')}
}
public static class Builder {
   ${strfields2:enclosed_bean_fields('private ${type} ${name};', '${newline}')}

   ${strfields3:enclosed_bean_fields('public Builder ${name}( ${type} ${name}) { this.${name} = ${name}; return this; }', '${newline}')}

   public ${enclosing_type} build() {
	   return new ${enclosing_type}(this);
   }
}
```
will produce these statements : 
```java
	private Person(Builder builder) {
		this.firstName = builder.firstName;
		this.lastName = builder.lastName;
		this.active = builder.active;
		this.age = builder.age;
	}

	public static class Builder {
		private String firstName;
		private String lastName;
		private Boolean active;
		private int age;

		public Builder firstName(String firstName) {
			this.firstName = firstName;
			return this;
		}

		public Builder lastName(String lastName) {
			this.lastName = lastName;
			return this;
		}

		public Builder active(Boolean active) {
			this.active = active;
			return this;
		}

		public Builder age(int age) {
			this.age = age;
			return this;
		}

		public Person build() {
			return new Person(this);
		}
	}
```

2018-12-18 17:09 UTC, romeara commented
@desprez Added #3 to add a link to formatting as suggested. Shall take an in-depth look at this after work - thank you for updating as requested so quickly, at first glance the overall implementation looks good :)

2018-12-19 01:58 UTC, romeara requested changes
Overall functionally, this looks good! A couple things I'd like to see adjusted before merging, mostly extraneous changes or minor format/consistency items.

Thanks!

2018-12-19 01:58 UTC, romeara commented on org.starchartlabs.eclipse.template.dynamic/src/main/java/org/starchartlabs/eclipse/template/dynamic/resolver/FieldInfo.java
> +
I'd like to see some javadoc on this just explaining it's basic function

2018-12-19 01:58 UTC, romeara commented on org.starchartlabs.eclipse.template.dynamic/src/main/java/org/starchartlabs/eclipse/template/dynamic/resolver/EnclosedBeanFieldsResolver.java
> +
The comment characters shouldn't be necessary on this

2018-12-19 01:58 UTC, romeara commented on org.starchartlabs.eclipse.template.dynamic.feature/feature.xml
> -      version="0.1.0.0"
I would like to avoid editing the version numbers or binary jars in a pull request like this

2018-12-19 08:25 UTC, desprez commented on org.starchartlabs.eclipse.template.dynamic.feature/feature.xml
> -      version="0.1.0.0"
I wanted to test before commit: changing version allowed me to check that the good plugin version is loaded in Eclipse. But I did not really want to submit this change. I have been developing for a long time but I am a beginner in PR ;-)

2018-12-19 20:31 UTC, romeara commented on org.starchartlabs.eclipse.template.dynamic.feature/feature.xml
> -      version="0.1.0.0"
That's perfectly fine, just git reset it to the original for the jars/version number files and that should take care of it

2018-12-28 05:48 UTC, romeara commented
@desprez This PR is almost ready to go - I had mentioned it in an in-line comment, but I'll pull it out to here so we can wrap this up. The main remaining thing I'd like to see is removing the version and artifact file changes that got pulled along with your code changes (you were right to test locally first, and thank you for doing so - we just want to remove those side effect changes from the actual changset)

To do this, run the following on your branch, then commit and push:

```
git checkout origin/master org.starchartlabs.eclipse.template.dynamic.feature/feature.xml
git checkout origin/master org.starchartlabs.eclipse.template.dynamic.site/artifacts.jar
git checkout origin/master org.starchartlabs.eclipse.template.dynamic.site/content.jar
git checkout origin/master org.starchartlabs.eclipse.template.dynamic.site/plugins/org.starchartlabs.eclipse.template.dynamic_0.1.0.0.jar
git checkout origin/master org.starchartlabs.eclipse.template.dynamic.site/site.xml
git checkout origin/master org.starchartlabs.eclipse.template.dynamic/META-INF/MANIFEST.MF
```

Sorry it took a bit to get back to this - had a lot going on with the holidays. Thank you for making all the adjustments we've requested previously - once these resets are squared away, we should be good to go!

2019-01-02 09:04 UTC, desprez commented
Hi and happy new year.
I have just commited requested changes.
I hope its fine now.

2019-01-02 17:52 UTC, romeara approved these changes

2019-01-02 17:53 UTC, merged

2019-01-02 17:54 UTC, romeara commented
@desprez Looks good to me! I have merged it into master.
For here, I will fix a couple known bugs and then create a release including these changes (including a release via GitHub - which will notify you if you have selected that in the watch menu)

Thank you again for contributing, it is greatly appreciated!